import { IMMERSION_GUARDRAILS, type LetmefreeExperience } from './types';

const defaultImmersionGuardrails = [...IMMERSION_GUARDRAILS];

export const EXPERIENCES: LetmefreeExperience[] = [
  {
    id: 'selfness-affect-evening-reset',
    title: '퇴근길 감정 정리 코칭',
    family: 'selfness_coaching',
    axis: 'selfness_affect',
    mode: 'coaching_dialogue',
    estimatedMinutes: 10,
    inputTriggers: ['오늘 너무 지쳤어', '혼자 감당하는 느낌이 들어', '퇴근길에 마음이 복잡해'],
    explorationQuestions: [
      '오늘 가장 혼자 감당하고 있다고 느낀 순간은 언제였나요?',
      '그때 가장 크게 남은 감정은 분노, 실망, 외로움 중 어디에 가까웠나요?',
    ],
    flow: ['감정 반영', '혼자 든 책임의 맥락 탐색', '오늘 내려놓아도 되는 것 정리', '회복 행동 1개 선택'],
    analysisReadoutSchema: ['오늘의 주된 감정', '혼자 감당한 책임', '회복을 위한 작은 행동'],
    actionItemSchema: ['오늘 밤 5분 동안 내려놓아도 되는 책임 하나 적기'],
    reminderRule: '오늘 밤 9시에 5분 회복 루틴 알림',
    safetyNotes: ['심리 진단이나 치료처럼 말하지 않기', '강한 무기력 표현이 있으면 전문 도움 안내'],
    auditDecision: 'CREATE',
    immersionGuardrails: defaultImmersionGuardrails,
  },
  {
    id: 'selfness-affect-leader-loneliness',
    title: '리더의 외로움 이름 붙이기',
    family: 'selfness_coaching',
    axis: 'selfness_affect',
    mode: 'reflection',
    estimatedMinutes: 5,
    inputTriggers: ['리더라서 외로워', '내 마음을 알아주는 사람이 없어', '말할 곳이 없어'],
    explorationQuestions: [
      '그 외로움은 인정받지 못함에 가까운가요, 기대고 싶은 사람이 없음에 가까운가요?',
      '오늘 누군가 한 명이 알아줬으면 했던 마음은 무엇인가요?',
    ],
    flow: ['외로움의 종류 구분', '기대했던 관계 확인', '필요한 지지 언어화', '연결 행동 1개 선택'],
    analysisReadoutSchema: ['외로움의 이름', '필요했던 지지', '연결을 위한 다음 행동'],
    actionItemSchema: ['이번 주 믿을 수 있는 한 사람에게 10분 대화 요청하기'],
    reminderRule: '내일 점심 전 연결 행동을 다시 묻기',
    safetyNotes: ['사용자의 외로움을 과장하거나 병리화하지 않기'],
    auditDecision: 'CREATE',
    immersionGuardrails: defaultImmersionGuardrails,
  },
  {
    id: 'selfness-strength-natural-win',
    title: '오늘 자연스럽게 잘한 일 발견',
    family: 'selfness_coaching',
    axis: 'selfness_strength',
    mode: 'reflection',
    estimatedMinutes: 5,
    inputTriggers: ['내 강점이 뭔지 모르겠어', '오늘 뭘 잘했는지 모르겠어', '자신감이 떨어져'],
    explorationQuestions: [
      '오늘 별다른 노력 없이도 자연스럽게 해결한 일은 무엇이었나요?',
      '주변 사람들은 어떤 순간에 당신을 찾나요?',
    ],
    flow: ['작은 성공 장면 회상', '반복 행동 패턴 추출', '강점 단어 후보 제안', '강점 활용 행동 선택'],
    analysisReadoutSchema: ['자연스러운 성공 장면', '반복되는 강점 패턴', '내일 활용할 강점 행동'],
    actionItemSchema: ['내일 회의에서 강점 행동 하나 의식적으로 사용하기'],
    reminderRule: '내일 출근길에 오늘 사용할 강점 하나 확인',
    safetyNotes: ['과장된 칭찬보다 관찰 근거 기반으로 반영하기'],
    auditDecision: 'CREATE',
    immersionGuardrails: defaultImmersionGuardrails,
  },
  {
    id: 'selfness-strength-core-sentence',
    title: '내 핵심역량 1문장 만들기',
    family: 'selfness_coaching',
    axis: 'selfness_strength',
    mode: 'coaching_dialogue',
    estimatedMinutes: 10,
    inputTriggers: ['내 핵심역량을 말하고 싶어', '리더로서 내가 잘하는 걸 정리하고 싶어', '나를 설명하는 문장이 필요해'],
    explorationQuestions: [
      '최근 3개월 동안 반복해서 성과가 났던 장면은 무엇인가요?',
      '그 장면에서 당신이 남들보다 다르게 본 것은 무엇인가요?',
    ],
    flow: ['성과 장면 수집', '관점/판단/행동 패턴 분리', '핵심역량 문장 초안', '현장 적용 예시 선택'],
    analysisReadoutSchema: ['반복 성과 패턴', '고유한 판단 기준', '핵심역량 1문장'],
    actionItemSchema: ['이번 주 자기소개/1:1에서 핵심역량 문장 한 번 사용하기'],
    reminderRule: '금요일 오후 핵심역량 문장이 실제로 맞았는지 회고 알림',
    safetyNotes: ['사용자의 정체성을 단정하지 않고 가설로 제안하기'],
    auditDecision: 'CREATE',
    immersionGuardrails: defaultImmersionGuardrails,
  },
  {
    id: 'selfness-calling-desire-clarity',
    title: '오늘 내가 진짜 원했던 것 말하기',
    family: 'selfness_coaching',
    axis: 'selfness_calling',
    mode: 'coaching_dialogue',
    estimatedMinutes: 10,
    inputTriggers: ['내가 진짜 원하는 게 뭔지 모르겠어', '욕망을 솔직하게 보고 싶어', '왜 이렇게 화가 나는지 모르겠어'],
    explorationQuestions: [
      '그 상황에서 겉으로 말한 요구 말고, 안쪽에서 진짜 원했던 것은 무엇이었나요?',
      '그 욕망을 부끄럽지 않게 말한다면 어떤 문장이 되나요?',
    ],
    flow: ['표면 감정 확인', '숨은 욕망 탐색', '의도와 책임 연결', '작은 실천 선택'],
    analysisReadoutSchema: ['표면 감정', '숨은 욕망', '책임 있게 표현할 문장'],
    actionItemSchema: ['오늘 한 문장으로 내 욕망을 기록하고 내일 행동 1개 정하기'],
    reminderRule: '내일 아침 욕망을 책임 있는 행동으로 바꾸는 알림',
    safetyNotes: ['욕망을 판단하지 않고 책임 있는 표현으로 연결하기'],
    auditDecision: 'CREATE',
    immersionGuardrails: defaultImmersionGuardrails,
  },
  {
    id: 'selfness-calling-weekly-intention',
    title: '이번 주 리더로서 지킬 의도 정하기',
    family: 'selfness_coaching',
    axis: 'selfness_calling',
    mode: 'reflection',
    estimatedMinutes: 5,
    inputTriggers: ['이번 주 어떻게 살지 정리하고 싶어', '리더로서 내 의도를 잡고 싶어', '중요한 선택 기준이 필요해'],
    explorationQuestions: [
      '이번 주 어떤 순간에도 지키고 싶은 리더의 태도는 무엇인가요?',
      '그 태도를 가장 시험할 가능성이 큰 상황은 무엇인가요?',
    ],
    flow: ['주간 맥락 확인', '의도 문장 작성', '시험 상황 예측', '보호 행동 1개 선택'],
    analysisReadoutSchema: ['이번 주 의도', '시험 상황', '의도를 지키는 행동'],
    actionItemSchema: ['월요일 첫 회의 전 의도 문장 읽기'],
    reminderRule: '매일 출근길에 이번 주 의도 문장 알림',
    safetyNotes: ['완벽한 실천보다 작고 반복 가능한 행동으로 제안하기'],
    auditDecision: 'CREATE',
    immersionGuardrails: defaultImmersionGuardrails,
  },
  {
    id: 'weness-diversity-perspective-taking',
    title: '이해되지 않는 팀원 관점 가설 세우기',
    family: 'weness_training',
    axis: 'weness_diversity',
    mode: 'roleplay',
    estimatedMinutes: 10,
    inputTriggers: ['저 팀원이 이해가 안 돼', '서로 너무 달라서 힘들어', '세대 차이가 커'],
    explorationQuestions: [
      '그 팀원의 행동 중 가장 이해하기 어려웠던 장면은 무엇인가요?',
      '그 행동 뒤에 있을 수 있는 선한 의도 가설을 하나만 세우면 무엇일까요?',
    ],
    flow: ['상황 장면화', '상대 관점 가설', '존중 언어 리허설', '확인 질문 연습'],
    analysisReadoutSchema: ['내 해석과 사실의 구분', '상대의 가능한 의도', '존중을 담은 확인 질문'],
    actionItemSchema: ['다음 1:1에서 확인 질문 1개 사용하기'],
    reminderRule: '다음 1:1 30분 전 확인 질문 리허설 알림',
    safetyNotes: ['상대를 고정된 유형으로 낙인찍지 않기'],
    auditDecision: 'REWRITE',
    sourceScenarioIds: ['team-clash', 'inter-gen-clash'],
    immersionGuardrails: defaultImmersionGuardrails,
  },
  {
    id: 'weness-diversity-care-boundary',
    title: '배려와 기준 사이 균형 잡기',
    family: 'weness_training',
    axis: 'weness_diversity',
    mode: 'rehearsal',
    estimatedMinutes: 10,
    inputTriggers: ['배려하다가 기준이 무너져', '어디까지 이해해야 할지 모르겠어', '팀원이 힘들어 보이는데 성과도 챙겨야 해'],
    explorationQuestions: [
      '지금 지켜야 할 기준은 무엇이고, 배려해야 할 사정은 무엇인가요?',
      '상대에게 존중을 주면서도 흐리지 말아야 할 요청은 무엇인가요?',
    ],
    flow: ['기준/배려 분리', '말해야 할 요청 정리', '따뜻하지만 명확한 문장 리허설', '다음 확인 기준 설정'],
    analysisReadoutSchema: ['지켜야 할 기준', '배려할 맥락', '따뜻하고 명확한 요청 문장'],
    actionItemSchema: ['오늘 기준과 지원을 함께 담은 3문장 전달하기'],
    reminderRule: '내일 오전 요청 후 반응을 점검하는 알림',
    safetyNotes: ['개인 사정을 캐묻지 않고 업무 기준과 지원 가능성을 중심으로 묻기'],
    auditDecision: 'REWRITE',
    sourceScenarioIds: ['silent-struggle', 'tmi-energy-drainer'],
    immersionGuardrails: defaultImmersionGuardrails,
  },
  {
    id: 'weness-feedback-30sec-feedforward',
    title: '30초 피드포워드 리허설',
    family: 'weness_training',
    axis: 'weness_feedback',
    mode: 'rehearsal',
    estimatedMinutes: 5,
    inputTriggers: ['피드백을 해야 하는데 뭐라고 말하지', '성과 면담이 부담돼', '비난처럼 들릴까 봐 걱정돼'],
    explorationQuestions: [
      '관찰한 행동을 평가 없이 말하면 어떤 문장인가요?',
      '앞으로 기대하는 행동은 무엇인가요?',
    ],
    flow: ['관찰 문장 만들기', '영향 설명', '기대 행동 제안', '30초 발화 연습'],
    analysisReadoutSchema: ['관찰의 명확성', '기대 행동의 구체성', '상대가 실행할 다음 한 걸음'],
    actionItemSchema: ['내일 1:1에서 관찰-영향-기대 3문장 말하기'],
    reminderRule: '내일 1:1 1시간 전 30초 리허설 알림',
    safetyNotes: ['인격 판단 대신 관찰 가능한 행동 중심으로 말하기'],
    auditDecision: 'MERGE',
    sourceScenarioIds: ['feedback-defense', 'unclear-instructions-confusion', 'perfectionist-report-delay'],
    immersionGuardrails: defaultImmersionGuardrails,
  },
  {
    id: 'weness-feedback-difficult-1on1',
    title: '어려운 1:1 대화 리허설',
    family: 'weness_training',
    axis: 'weness_feedback',
    mode: 'roleplay',
    estimatedMinutes: 15,
    inputTriggers: ['어려운 1:1을 앞두고 있어', '팀원이 방어적으로 나올까 봐 걱정돼', '민감한 이야기를 해야 해'],
    explorationQuestions: [
      '이 대화가 끝났을 때 상대가 무엇을 이해하면 좋겠나요?',
      '상대가 가장 방어적으로 반응할 지점은 어디인가요?',
    ],
    flow: ['대화 목표 설정', '상대 반응 예상', 'AI 팀원 역할극', '재시도와 문장 개선', '현장 적용 문장 확정'],
    analysisReadoutSchema: ['대화 목표의 선명도', '방어 반응 대응력', '다음 대화 첫 문장'],
    actionItemSchema: ['1:1 시작 문장과 마무리 요청 문장 저장하기'],
    reminderRule: '1:1 당일 아침 시작 문장 리마인드',
    safetyNotes: ['위협/강압보다 경계와 요청을 명확히 하는 방향으로 훈련'],
    auditDecision: 'MERGE',
    sourceScenarioIds: ['fragile-ego-feedback', 'transparency-demand', 'promotion-fail'],
    immersionGuardrails: defaultImmersionGuardrails,
  },
  {
    id: 'weness-execution-weekly-goal',
    title: '이번 주 팀 목표 1문장 정리',
    family: 'weness_training',
    axis: 'weness_execution',
    mode: 'planning_drill',
    estimatedMinutes: 10,
    inputTriggers: ['팀 목표가 흐릿해', '이번 주 무엇에 집중할지 모르겠어', '팀원들에게 방향을 공유해야 해'],
    explorationQuestions: [
      '이번 주 팀이 반드시 만들어야 하는 변화는 무엇인가요?',
      '그 변화를 팀원이 이해할 수 있는 한 문장으로 말하면 무엇인가요?',
    ],
    flow: ['상위 목표 확인', '이번 주 결과 정의', '팀 공유 1문장 작성', '역할별 첫 행동 분리'],
    analysisReadoutSchema: ['팀 목표 1문장', '역할별 첫 행동', '확인할 지표'],
    actionItemSchema: ['월요일 스탠드업에서 목표 1문장 공유하기'],
    reminderRule: '월요일 오전 스탠드업 30분 전 목표 문장 알림',
    safetyNotes: ['목표를 과도하게 넓히지 않고 1주 단위로 제한'],
    auditDecision: 'REWRITE',
    sourceScenarioIds: ['new-hire-lost', 'always-last-minute'],
    immersionGuardrails: defaultImmersionGuardrails,
  },
  {
    id: 'weness-execution-small-hypothesis',
    title: '가장 작은 검증 가설 세우기',
    family: 'weness_training',
    axis: 'weness_execution',
    mode: 'planning_drill',
    estimatedMinutes: 10,
    inputTriggers: ['실행이 안 돼', '가설을 작게 만들고 싶어', '팀이 계속 말만 하고 움직이지 않아'],
    explorationQuestions: [
      '지금 팀이 가장 먼저 확인해야 할 불확실성은 무엇인가요?',
      '하루 안에 검증할 수 있을 만큼 작게 만들면 어떤 실행이 되나요?',
    ],
    flow: ['불확실성 선택', '가설 문장 작성', '24시간 실행 정의', '회고 질문 3개 설정'],
    analysisReadoutSchema: ['가장 작은 가설', '24시간 실행', '회고 질문'],
    actionItemSchema: ['내일 안에 1개 실험 실행 후 회고 질문 기록'],
    reminderRule: '내일 오후 5시에 실험 결과 회고 알림',
    safetyNotes: ['큰 전략 논쟁보다 작고 안전한 검증 행동으로 낮추기'],
    auditDecision: 'REWRITE',
    sourceScenarioIds: ['quality-vs-speed', 'eighty-percent-finisher', 'over-commitment'],
    immersionGuardrails: defaultImmersionGuardrails,
  },
];
